name: 'Continuous Integration'

on:
  workflow_call:

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - develop
      - main

env: ${{ vars }}

permissions:
  contents: read
  packages: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: |
          uv python install

      - name: Install the project
        run: |
          uv sync --dev

      - name: Run Ruff
        run: |
          uv run ruff check --output-format=github

      - name: Run Pyrefly Type Checker
        run: |
          uv run pyrefly check --output-format=github

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: |
          uv python install

      - name: Install the project
        run: |
          uv sync --all-groups

      - name: Test with pytest
        run: |
          echo "Running tests..."
          make model-test
          make api-test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: |
          uv python install

      - name: Install the project
        run: |
          uv sync --no-dev

      - name: Build package
        run: |
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
